FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["../src/MonitoringSLN/Monitoring.General/", "Monitoring.General/"]
RUN dotnet restore "Monitoring.General/Monitoring.General.csproj"

COPY . .

WORKDIR "/src/"

RUN dotnet build "Monitoring.General/Monitoring.General.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Monitoring.General/Monitoring.General.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Monitoring.General.dll"]
