FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

COPY ["src/MonitoringSLN/Monitoring.Basic/", "Monitoring.Basic/"]
RUN dotnet restore "Monitoring.OpenTelemetryExport/Monitoring.OpenTelemetryExport.csproj"

COPY . .

RUN dotnet build "Monitoring.OpenTelemetryExport/Monitoring.OpenTelemetryExport.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Monitoring.OpenTelemetryExport/Monitoring.OpenTelemetryExport.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Monitoring.OpenTelemetryExport.dll"]
